<a href="https://colab.research.google.com/github/afzal/pytorch-N4/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


In [11]:
import numpy as np

In [7]:
tensor_2d = torch.randn(2,3)
tensor_2d

tensor([[ 0.6661, -0.3493,  0.1955],
        [-0.6966,  0.5642, -0.1681]])

In [9]:
tensor_3d = torch.zeros (5,2,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [12]:
np1 = np.random.rand(2,3)
np1

array([[0.44116982, 0.24302152, 0.20981926],
       [0.90990954, 0.90241143, 0.28499997]])

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4412, 0.2430, 0.2098],
        [0.9099, 0.9024, 0.2850]], dtype=torch.float64)